// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Technical Support",
            "url": "http://www.swagger.io/support",
            "email": "[EMAIL_ADDRESS]"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/products": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mencari dan menampilkan daftar produk untuk suatu toko",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Menampilkan daftar produk dengan pagination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Store ID",
                        "name": "store_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Keyword nama produk",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Nomor Halaman",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Ukuran Halaman",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-array_github_com_PetaFlops-web_backend-shop-smbk_internal_modules_product_src_model_ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Membuat entri produk baru untuk toko tertentu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Menambahkan data produk baru",
                "parameters": [
                    {
                        "description": "Data Produk",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_product_src_model.CreateProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_product_src_model_ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil data produk berdasarkan ID dan Store ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Menampilkan detail satu produk",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Store ID",
                        "name": "store_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_product_src_model_ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengubah detail produk berdasarkan ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Mengubah data produk yang sudah ada",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Data Produk",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_product_src_model.UpdateProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_product_src_model_ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghapus data produk berdasarkan ID dan Store ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "Menghapus produk",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Store ID",
                        "name": "store_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-any"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/reports/daily": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghitung laporan harian toko secara on-the-fly berdasarkan transaksi dan stok terkini",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Report"
                ],
                "summary": "Menampilkan laporan harian",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Store ID",
                        "name": "store_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tanggal laporan (YYYY-MM-DD)",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_report_src_model_DailyReportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/restock-predictions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan prediksi restock tersimpan untuk toko",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Restock"
                ],
                "summary": "Menampilkan prediksi restock",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Store ID",
                        "name": "store_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-array_github_com_PetaFlops-web_backend-shop-smbk_internal_modules_restock_src_model_RestockPredictionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/restock-predictions/_generate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil histori transaksi, memanggil ML inventory prediction, lalu menyimpan rekomendasi restock toko",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Restock"
                ],
                "summary": "Generate prediksi restock",
                "parameters": [
                    {
                        "description": "Parameter prediksi restock",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_restock_src_model.GenerateRestockPredictionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_restock_src_model_GenerateRestockPredictionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/stores": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the store of the currently authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store"
                ],
                "summary": "Get",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_store_src_model_StoreResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the store of the currently authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "description": "Store update details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_store_src_model.StoreRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_store_src_model_StoreResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new store for the currently authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Store"
                ],
                "summary": "Create a new store",
                "parameters": [
                    {
                        "description": "Store details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_store_src_model.StoreRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_store_src_model_StoreResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan daftar transaksi toko dengan pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Menampilkan riwayat transaksi",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Store ID",
                        "name": "store_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Nomor Halaman",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Ukuran Halaman",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-array_github_com_PetaFlops-web_backend-shop-smbk_internal_modules_transaction_src_model_TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menyimpan transaksi yang telah direview oleh user dan mengurangi stok produk",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Konfirmasi \u0026 simpan transaksi",
                "parameters": [
                    {
                        "description": "Data Transaksi Final",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_transaction_src_model.CreateTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_transaction_src_model_TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/transactions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil data transaksi beserta daftar item-nya",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Menampilkan detail satu transaksi",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Store ID",
                        "name": "store_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_transaction_src_model_TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghapus data transaksi dan mengembalikan stok produk (increment)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Menghapus transaksi",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Store ID",
                        "name": "store_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-any"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Creates a new user with username and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new merchant user",
                "parameters": [
                    {
                        "description": "Register Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_auth_src_model.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_auth_src_model_AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/_current": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the profile of the currently authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get current logged-in user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_auth_src_model_UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/_login": {
            "post": {
                "description": "Authenticates a user and returns a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login merchant user",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_auth_src_model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_auth_src_model_AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_auth_src_model.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_auth_src_model.UserResponse"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_auth_src_model.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_auth_src_model.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 255
                },
                "password": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 6
                },
                "username": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_auth_src_model.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_product_src_model.CreateProductRequest": {
            "type": "object",
            "required": [
                "product_name",
                "selling_price",
                "store_id",
                "unit"
            ],
            "properties": {
                "cost_price": {
                    "type": "integer",
                    "minimum": 0
                },
                "product_name": {
                    "type": "string"
                },
                "selling_price": {
                    "type": "integer",
                    "minimum": 0
                },
                "stock": {
                    "type": "integer",
                    "minimum": 0
                },
                "store_id": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_product_src_model.ProductResponse": {
            "type": "object",
            "properties": {
                "cost_price": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "selling_price": {
                    "type": "integer"
                },
                "stock": {
                    "type": "integer"
                },
                "store_id": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_product_src_model.UpdateProductRequest": {
            "type": "object",
            "required": [
                "product_name",
                "selling_price",
                "store_id",
                "unit"
            ],
            "properties": {
                "cost_price": {
                    "type": "integer",
                    "minimum": 0
                },
                "product_name": {
                    "type": "string"
                },
                "selling_price": {
                    "type": "integer",
                    "minimum": 0
                },
                "stock": {
                    "type": "integer",
                    "minimum": 0
                },
                "store_id": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_report_src_model.BestSellingProductResponse": {
            "type": "object",
            "properties": {
                "current_stock": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "qty_sold": {
                    "type": "integer"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_report_src_model.DailyReportResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "jumlah_transaksi": {
                    "type": "integer"
                },
                "produk_terlaris": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_report_src_model.BestSellingProductResponse"
                    }
                },
                "sisa_stok": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_report_src_model.StockSummaryResponse"
                    }
                },
                "store": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_report_src_model.StoreSummaryResponse"
                },
                "total_omset": {
                    "type": "integer"
                },
                "total_untung": {
                    "type": "integer"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_report_src_model.StockSummaryResponse": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "stock": {
                    "type": "integer"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_report_src_model.StoreSummaryResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "store_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_restock_src_model.GenerateRestockPredictionRequest": {
            "type": "object",
            "required": [
                "store_id"
            ],
            "properties": {
                "forecast_date": {
                    "type": "string"
                },
                "history_days": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "string"
                },
                "store_id": {
                    "type": "string"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_restock_src_model.GenerateRestockPredictionResponse": {
            "type": "object",
            "properties": {
                "generated_count": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_restock_src_model.RestockPredictionResponse"
                    }
                },
                "skipped": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_restock_src_model.RestockSkippedItemResponse"
                    }
                },
                "skipped_count": {
                    "type": "integer"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_restock_src_model.RestockPredictionResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "current_stock": {
                    "type": "integer"
                },
                "daily_sales": {
                    "type": "integer"
                },
                "forecast_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "recommended_restock_qty": {
                    "type": "integer"
                },
                "store_id": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_restock_src_model.RestockSkippedItemResponse": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_store_src_model.StoreRequest": {
            "type": "object",
            "required": [
                "store_name"
            ],
            "properties": {
                "store_name": {
                    "type": "string",
                    "minLength": 3
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_store_src_model.StoreResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "store_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_transaction_src_model.CreateTransactionRequest": {
            "type": "object",
            "required": [
                "items",
                "source",
                "store_id"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_transaction_src_model.TransactionItemRequest"
                    }
                },
                "source": {
                    "type": "string"
                },
                "store_id": {
                    "type": "string"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_transaction_src_model.TransactionItemRequest": {
            "type": "object",
            "required": [
                "product_id",
                "qty",
                "selling_price_final"
            ],
            "properties": {
                "product_id": {
                    "type": "string"
                },
                "qty": {
                    "type": "integer",
                    "minimum": 1
                },
                "selling_price_final": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_transaction_src_model.TransactionItemResponse": {
            "type": "object",
            "properties": {
                "cost_price_snapshot": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "product_name_snapshot": {
                    "type": "string"
                },
                "qty": {
                    "type": "integer"
                },
                "selling_price_snapshot": {
                    "type": "integer"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_modules_transaction_src_model.TransactionResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_transaction_src_model.TransactionItemResponse"
                    }
                },
                "source": {
                    "type": "string"
                },
                "store_id": {
                    "type": "string"
                },
                "transaction_date": {
                    "type": "string"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.ApiErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "message": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.PageMetadata": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total_item": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "paging": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.PageMetadata"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-array_github_com_PetaFlops-web_backend-shop-smbk_internal_modules_product_src_model_ProductResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_product_src_model.ProductResponse"
                    }
                },
                "message": {
                    "type": "string"
                },
                "paging": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.PageMetadata"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-array_github_com_PetaFlops-web_backend-shop-smbk_internal_modules_restock_src_model_RestockPredictionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_restock_src_model.RestockPredictionResponse"
                    }
                },
                "message": {
                    "type": "string"
                },
                "paging": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.PageMetadata"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-array_github_com_PetaFlops-web_backend-shop-smbk_internal_modules_transaction_src_model_TransactionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_transaction_src_model.TransactionResponse"
                    }
                },
                "message": {
                    "type": "string"
                },
                "paging": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.PageMetadata"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_auth_src_model_AuthResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_auth_src_model.AuthResponse"
                },
                "message": {
                    "type": "string"
                },
                "paging": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.PageMetadata"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_auth_src_model_UserResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_auth_src_model.UserResponse"
                },
                "message": {
                    "type": "string"
                },
                "paging": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.PageMetadata"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_product_src_model_ProductResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_product_src_model.ProductResponse"
                },
                "message": {
                    "type": "string"
                },
                "paging": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.PageMetadata"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_report_src_model_DailyReportResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_report_src_model.DailyReportResponse"
                },
                "message": {
                    "type": "string"
                },
                "paging": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.PageMetadata"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_restock_src_model_GenerateRestockPredictionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_restock_src_model.GenerateRestockPredictionResponse"
                },
                "message": {
                    "type": "string"
                },
                "paging": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.PageMetadata"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_store_src_model_StoreResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_store_src_model.StoreResponse"
                },
                "message": {
                    "type": "string"
                },
                "paging": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.PageMetadata"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.WebResponse-github_com_PetaFlops-web_backend-shop-smbk_internal_modules_transaction_src_model_TransactionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_modules_transaction_src_model.TransactionResponse"
                },
                "message": {
                    "type": "string"
                },
                "paging": {
                    "$ref": "#/definitions/github_com_PetaFlops-web_backend-shop-smbk_internal_shared_response.PageMetadata"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "AIC Backend API",
	Description:      "API Documentation for AIC Backend.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
